# .travis.yml for python-clang
#

sudo: required
dist: trusty

language: python

python:
  - "2.7"
  - "3.6"


install:
# travis-ci use trusty, with py27, py36 and clang5
  - sudo apt-get install libclang1-5.0 libclang-5.0-dev  --yes --force-yes
  - pip install coveralls

script:
# run tests
  - python setup.py test
  - coverage run --source=clang setup.py test

after_success:
  coveralls

# disable email notifications
notifications:
  email:
    on_success: never
    on_failure: never
